/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mobile.crudfoodview;

import Mobile.crudfoodmodel.Food;
import Mobile.crudfoodmodel.FoodModel;
import Mobile.crudmoodmodel.Mood;
import Mobile.crudmoodmodel.MoodModel;
import Mobile.userprofilemodel.Profile;
import java.text.SimpleDateFormat;
import Mobile.mainmenuview.MainMenu;
import Mobile.notificationsctrl.NotificationsController;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Arrays;

/**
 *
 * @author Ben
 */
public class NewEntryView extends javax.swing.JFrame {

    private Profile prof;
    FoodModel foodDB = new FoodModel();
    MoodModel moodDB = new MoodModel();
    private MainMenu mm;
    NotificationsController nc;

    /**
     * Creates new form NewEntryView
     */
    public NewEntryView(MainMenu mm) {
        this.mm = mm;
        initComponents();
        prof = MainMenu.prof;
        this.getContentPane().setBackground(new java.awt.Color(66, 69, 71));
        
        //Spawns frame in center of monitor
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation( (dim.width/2-this.getSize().width/2) + 65, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foodEntryLabel = new javax.swing.JLabel();
        foodEntryTextField = new javax.swing.JTextField();
        moodEntryLabel = new javax.swing.JLabel();
        moodComboBox = new javax.swing.JComboBox<>();
        cancelButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        foodEntryLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        foodEntryLabel.setText("Food:");

        moodEntryLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        moodEntryLabel.setText("Mood:");

        moodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select one-", "Enter Later", "Happy", "Sad", "Silly", "Angry", "Sick", "Disappointed", "Frustrated", "Proud", "Excited", "Scared", "Suprised", "Nervous" }));
        moodComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moodComboBoxActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.setEnabled(false);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(foodEntryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(foodEntryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(moodEntryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodEntryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodEntryLabel))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moodEntryLabel)
                    .addComponent(moodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(submitButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String timeStamp = new SimpleDateFormat("yyyy.MM.dd.HH.mm").format(new java.util.Date());

        if (moodComboBox.getSelectedIndex() == 1) {
            //Mood mood = new Mood("*/&%");
            Food foodNoMood = new Food(foodEntryTextField.getText(), timeStamp, "*/&%");
            nc = new NotificationsController(foodNoMood);
            nc.startTimer();
            foodDB.postFood(prof, foodNoMood);
        } else {
            //Mood mood = new Mood((String) moodComboBox.getSelectedItem());
            Food food = new Food(foodEntryTextField.getText(), timeStamp, (String) moodComboBox.getSelectedItem());
            foodDB.postFood(prof, food);
        }

        dispose();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void moodComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moodComboBoxActionPerformed
        final boolean submitEnabled = moodComboBox.getSelectedIndex() == 0;
        submitButton.setEnabled(!submitEnabled);
    }//GEN-LAST:event_moodComboBoxActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        mm.buttonEnable(mm.foodMoodEntryButton);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel foodEntryLabel;
    private javax.swing.JTextField foodEntryTextField;
    private javax.swing.JComboBox<String> moodComboBox;
    private javax.swing.JLabel moodEntryLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
