/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mobile.notificationsview;

import Mobile.crudfoodmodel.Food;
import Mobile.crudfoodmodel.FoodModel;
import Mobile.crudmoodmodel.MoodModel;
import Mobile.mainmenuview.MainMenu;
import Mobile.userprofilemodel.Profile;
import java.text.SimpleDateFormat;

/**
 *
 * @author Ben
 */
public class NotificationsView extends javax.swing.JFrame {

    private Profile prof;
    FoodModel foodDB = new FoodModel();
    MoodModel moodDB = new MoodModel();
    Food desiredFood;

    /**
     * Creates new form NotificationsView
     */
    public NotificationsView(Food food) {
        initComponents();
        prof = MainMenu.prof;
        food = desiredFood;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notiFoodLabel = new javax.swing.JLabel();
        moodEntryLabel = new javax.swing.JLabel();
        moodComboBox = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        notiFoodLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        notiFoodLabel.setText("Food:");

        moodEntryLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        moodEntryLabel.setText("Mood:");

        moodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select one-", "Happy", "Sad", "Silly", "Angry", "Sick", "Disappointed", "Frustrated", "Proud", "Excited", "Scared", "Suprised", "Nervous" }));
        moodComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moodComboBoxActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.setEnabled(false);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notiFoodLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(moodEntryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notiFoodLabel)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moodEntryLabel)
                    .addComponent(moodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moodComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moodComboBoxActionPerformed
        final boolean submitEnabled = moodComboBox.getSelectedIndex() == 0;
        submitButton.setEnabled(!submitEnabled);
    }//GEN-LAST:event_moodComboBoxActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        desiredFood.setFoodMood( (String) moodComboBox.getSelectedItem() );
        dispose();
    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> moodComboBox;
    private javax.swing.JLabel moodEntryLabel;
    private javax.swing.JLabel notiFoodLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
